import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import Header from './Header';
import FormModal from './FormModal';
import './PrivacyPolicy.css';

const PrivacyPolicy = () => {
  const [isFormOpen, setIsFormOpen] = useState(false);

  const handleOpenForm = () => {
    setIsFormOpen(true);
  };

  const handleCloseForm = () => {
    setIsFormOpen(false);
  };

  return (
    <div className="privacy-policy-page">
      {/* Header */}
      <Header onOpenForm={handleOpenForm} />

      {/* Main Content */}
      <main className="privacy-main">
        <div className="container">
          <motion.h1 
            className="privacy-title"
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            PRIVACY POLICY
          </motion.h1>

          <motion.div 
            className="privacy-content"
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            {/* Overview Section */}
            <section className="privacy-section">
              <h2>Overview</h2>
              <p>
                We, Mission Control, operating as a branding agency and creative capital partner for high-growth startups, are committed to protecting your privacy and ensuring the security of your personal information.
              </p>
              <p>
                We only have limited data collection and usage practices for the purpose of providing our services to you and improving our services. This Privacy Policy explains how we collect, use, and protect your information.
              </p>
              <p>
                This Privacy Policy applies to all Mission Control services, including our website, consulting services, and any other services we provide. By using our services, you agree to the collection and use of information in accordance with this policy.
              </p>
            </section>

            {/* Definitions Section */}
            <section className="privacy-section">
              <h2>Definitions</h2>
              <ul>
                <li><strong>Company</strong> (referred to as either "the Company", "we", "us" or "our") refers to Mission Control.</li>
                <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                <li><strong>Service</strong> refers to the Website, consulting services, and any other services provided by Mission Control.</li>
                <li><strong>You</strong> refers to the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.</li>
                <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website.</li>
              </ul>
            </section>

            {/* Collecting and Using Personal Data Section */}
            <section className="privacy-section">
              <h2>Collecting and Using Your Personal Data</h2>
              
              <h3>Types of Data Collected</h3>
              
              <h4>Personal Data</h4>
              <p>
                While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:
              </p>
              <ul>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Usage Data</li>
              </ul>

              <h4>Usage Data</h4>
              <p>
                Usage Data is collected automatically when using the Service.
              </p>
              <p>
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>
              <p>
                When You access the Service by or through a mobile device, we may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
              </p>

              <h4>Tracking Technologies and Cookies</h4>
              <p>
                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
              </p>
            </section>
          </motion.div>
        </div>
      </main>

      {/* CTA Section */}
      <section className="privacy-cta">
        <div className="container">
          <motion.div 
            className="cta-content"
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
          >
            <h2 className="cta-title">NOW ACCEPTING<br />SELECT NEW CLIENTS</h2>
            <p className="cta-subtitle">2 of 5 spots available for Fall 2025</p>
            <button className="start-mission-btn" onClick={handleOpenForm}>
              <div className="btn-content">
                <span>START YOUR MISSION</span>
                <div className="arrow-icon">→</div>
              </div>
            </button>
          </motion.div>
        </div>
      </section>

      {/* Footer */}
      <footer className="privacy-footer">
        <div className="container">
          <div className="footer-content">
            <div className="footer-main">
              <h1 className="footer-logo">MISSION CONTROL</h1>
              <p className="footer-description">
                A branding agency and creative capital partner<br />
                for high-growth startups
              </p>
            </div>
            <div className="footer-social">
              <a href="#" className="social-link">INSTAGRAM</a>
              <a href="#" className="social-link">FACEBOOK</a>
              <a href="#" className="social-link">LINKEDIN</a>
              <a href="#" className="social-link">X</a>
            </div>
          </div>
          <div className="footer-bottom">
            <div className="footer-bottom-left">
              <p>© Mission Control Company 2025</p>
            </div>
            <div className="footer-bottom-center">
              <p>San Francisco, CA — Planet Earth</p>
            </div>
            <div className="footer-bottom-right">
              <Link to="/privacy-policy" className="footer-link">Privacy Policy</Link>
            </div>
          </div>
        </div>
      </footer>
      <FormModal isOpen={isFormOpen} onClose={handleCloseForm} />
    </div>
  );
};

export default PrivacyPolicy;